name: ob_havo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.2
  weather: ^3.1.1
  intl: ^0.20.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "logo/1.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "logo/1.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "logo/1.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "logo/1.png"
  adaptive_icon_background: "#00000000"
  adaptive_icon_foreground: "logo/1.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
 

flutter:
  uses-material-design: true
  assets:
    - assets/
    - logo/